### ISSUE TITLE
request: feature/avatar 브랜치 코드 리뷰 요청

### ISSUE THREAD

**Issue by changhui-chan** [changhui-chan/10-Sprint-Fandom-K#24]
## 이슈
- 헤더 작업하면서 해당 컴포넌트가 필요했기 때문에 미리 merge 합니다. feature/avatar 브랜치 코드 리뷰 부탁드립니다.
- 나중에 깨달은 건데 className styles.avatar로 해야하는데 습관적으로 .container로 한 거 같네요 리팩토링 단계 때 고칠게요
#23

**Comment by najitwo** [comment]
완료
